// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {output} from '../models';

export function DeleteOutput(arg1:string,arg2:string):Promise<void>;

export function ListOutputs(arg1:string):Promise<Array<output.OutputFile>>;
