// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function ApplyToWorkspace():Promise<void>;

export function CreatePreset(arg1:string):Promise<Array<settings.PresetMeta>>;

export function DeletePreset(arg1:string):Promise<Array<settings.PresetMeta>>;

export function FetchModels(arg1:string,arg2:Record<string, string>):Promise<settings.ModelResult>;

export function GetSettings(arg1:boolean):Promise<Array<settings.SettingItem>>;

export function ListPresets():Promise<Array<settings.PresetMeta>>;

export function RenamePreset(arg1:string,arg2:string):Promise<Array<settings.PresetMeta>>;

export function ResolveAll():Promise<Record<string, string>>;

export function SaveSettings(arg1:Record<string, string>):Promise<Array<settings.SettingItem>>;

export function SetActivePreset(arg1:string):Promise<Array<settings.SettingItem>>;

export function TestSettings(arg1:string,arg2:Record<string, string>):Promise<settings.ProbeResult>;
