// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyToWorkspace() {
  return window['go']['settings']['Service']['ApplyToWorkspace']();
}

export function CreatePreset(arg1) {
  return window['go']['settings']['Service']['CreatePreset'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['settings']['Service']['DeletePreset'](arg1);
}

export function FetchModels(arg1, arg2) {
  return window['go']['settings']['Service']['FetchModels'](arg1, arg2);
}

export function GetSettings(arg1) {
  return window['go']['settings']['Service']['GetSettings'](arg1);
}

export function ListPresets() {
  return window['go']['settings']['Service']['ListPresets']();
}

export function RenamePreset(arg1, arg2) {
  return window['go']['settings']['Service']['RenamePreset'](arg1, arg2);
}

export function ResolveAll() {
  return window['go']['settings']['Service']['ResolveAll']();
}

export function SaveSettings(arg1) {
  return window['go']['settings']['Service']['SaveSettings'](arg1);
}

export function SetActivePreset(arg1) {
  return window['go']['settings']['Service']['SetActivePreset'](arg1);
}

export function TestSettings(arg1, arg2) {
  return window['go']['settings']['Service']['TestSettings'](arg1, arg2);
}
