// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateStyle(arg1) {
  return window['go']['style']['Service']['CreateStyle'](arg1);
}

export function DeleteImage(arg1, arg2) {
  return window['go']['style']['Service']['DeleteImage'](arg1, arg2);
}

export function DeleteStyle(arg1) {
  return window['go']['style']['Service']['DeleteStyle'](arg1);
}

export function GenerateStylePrompt(arg1, arg2) {
  return window['go']['style']['Service']['GenerateStylePrompt'](arg1, arg2);
}

export function GetStyle(arg1) {
  return window['go']['style']['Service']['GetStyle'](arg1);
}

export function ListImages(arg1) {
  return window['go']['style']['Service']['ListImages'](arg1);
}

export function ListStyles() {
  return window['go']['style']['Service']['ListStyles']();
}

export function UpdateStyle(arg1, arg2) {
  return window['go']['style']['Service']['UpdateStyle'](arg1, arg2);
}

export function UploadImage(arg1, arg2, arg3) {
  return window['go']['style']['Service']['UploadImage'](arg1, arg2, arg3);
}
