// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {style} from '../models';

export function CreateStyle(arg1:style.StyleInput):Promise<style.Style>;

export function DeleteImage(arg1:string,arg2:string):Promise<void>;

export function DeleteStyle(arg1:string):Promise<void>;

export function GenerateStylePrompt(arg1:string,arg2:Array<string>):Promise<string>;

export function GetStyle(arg1:string):Promise<style.Style>;

export function ListImages(arg1:string):Promise<Array<string>>;

export function ListStyles():Promise<Array<style.Style>>;

export function UpdateStyle(arg1:string,arg2:style.StyleInput):Promise<style.Style>;

export function UploadImage(arg1:string,arg2:string,arg3:string):Promise<void>;
