// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['job']['Service']['CancelJob'](arg1);
}

export function ClearCompleted() {
  return window['go']['job']['Service']['ClearCompleted']();
}

export function GetJob(arg1) {
  return window['go']['job']['Service']['GetJob'](arg1);
}

export function JobLogs(arg1) {
  return window['go']['job']['Service']['JobLogs'](arg1);
}

export function ListJobs() {
  return window['go']['job']['Service']['ListJobs']();
}

export function Register(arg1, arg2) {
  return window['go']['job']['Service']['Register'](arg1, arg2);
}

export function SetEmitContext(arg1) {
  return window['go']['job']['Service']['SetEmitContext'](arg1);
}

export function SetJobTimeoutFn(arg1) {
  return window['go']['job']['Service']['SetJobTimeoutFn'](arg1);
}

export function Start() {
  return window['go']['job']['Service']['Start']();
}

export function StartJob(arg1, arg2, arg3) {
  return window['go']['job']['Service']['StartJob'](arg1, arg2, arg3);
}

export function Stop() {
  return window['go']['job']['Service']['Stop']();
}
