// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {job} from '../models';
import {context} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function ClearCompleted():Promise<number>;

export function ClearCompletedFor(arg1:string):Promise<number>;

export function GetJob(arg1:string):Promise<job.Job>;

export function JobLogs(arg1:string):Promise<string>;

export function ListJobs():Promise<Array<job.Job>>;

export function Register(arg1:string,arg2:job.Runner):Promise<void>;

export function SetEmitContext(arg1:context.Context):Promise<void>;

export function SetJobTimeoutFn(arg1:any):Promise<void>;

export function Start():Promise<void>;

export function StartJob(arg1:string,arg2:string,arg3:Record<string, any>):Promise<job.Job>;

export function Stop():Promise<void>;
