// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {context} from '../models';

export function GetFileServerPort():Promise<number>;

export function OpenImageFiles():Promise<Array<string>>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function OpenProductFolder(arg1:string):Promise<void>;

export function OpenWorkspace():Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function RuntimeInfo():Promise<system.RuntimeInfo>;

export function SetContext(arg1:context.Context):Promise<void>;
