// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileServerPort() {
  return window['go']['system']['Service']['GetFileServerPort']();
}

export function OpenImageFiles() {
  return window['go']['system']['Service']['OpenImageFiles']();
}

export function OpenInEditor(arg1) {
  return window['go']['system']['Service']['OpenInEditor'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['system']['Service']['OpenInFileManager'](arg1);
}

export function OpenOutputFolder(arg1) {
  return window['go']['system']['Service']['OpenOutputFolder'](arg1);
}

export function OpenProductFolder(arg1) {
  return window['go']['system']['Service']['OpenProductFolder'](arg1);
}

export function OpenWorkspace() {
  return window['go']['system']['Service']['OpenWorkspace']();
}

export function PickDirectory(arg1) {
  return window['go']['system']['Service']['PickDirectory'](arg1);
}

export function RuntimeInfo() {
  return window['go']['system']['Service']['RuntimeInfo']();
}

export function SetContext(arg1) {
  return window['go']['system']['Service']['SetContext'](arg1);
}
