// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {product} from '../models';

export function DeleteProduct(arg1:string):Promise<void>;

export function DeleteProductImage(arg1:string,arg2:string):Promise<void>;

export function GetProduct(arg1:string):Promise<product.ProductDetail>;

export function ListProducts():Promise<Array<product.Product>>;

export function SaveProduct(arg1:product.Product):Promise<product.ProductDetail>;

export function UploadProductImage(arg1:string,arg2:string,arg3:string):Promise<product.ProductImage>;

export function UploadProductImageFromPath(arg1:string,arg2:string):Promise<product.ProductImage>;
