// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProduct(arg1) {
  return window['go']['product']['Service']['DeleteProduct'](arg1);
}

export function DeleteProductImage(arg1, arg2) {
  return window['go']['product']['Service']['DeleteProductImage'](arg1, arg2);
}

export function GetProduct(arg1) {
  return window['go']['product']['Service']['GetProduct'](arg1);
}

export function ListProducts() {
  return window['go']['product']['Service']['ListProducts']();
}

export function SaveProduct(arg1) {
  return window['go']['product']['Service']['SaveProduct'](arg1);
}

export function UploadProductImage(arg1, arg2, arg3) {
  return window['go']['product']['Service']['UploadProductImage'](arg1, arg2, arg3);
}

export function UploadProductImageFromPath(arg1, arg2) {
  return window['go']['product']['Service']['UploadProductImageFromPath'](arg1, arg2);
}
