// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cache} from '../models';

export function CacheFilePath(arg1:string):Promise<string>;

export function ClearCaches(arg1:Array<string>):Promise<Array<string>>;

export function ClearGroup(arg1:string):Promise<Array<string>>;

export function ListCaches():Promise<Array<cache.CacheItem>>;

export function PlanFor(arg1:string):Promise<string>;

export function ReadCacheFile(arg1:string):Promise<string>;

export function WriteCacheFile(arg1:string,arg2:string):Promise<void>;
