// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CacheFilePath(arg1) {
  return window['go']['cache']['Service']['CacheFilePath'](arg1);
}

export function ClearCaches(arg1) {
  return window['go']['cache']['Service']['ClearCaches'](arg1);
}

export function ClearGroup(arg1) {
  return window['go']['cache']['Service']['ClearGroup'](arg1);
}

export function ListCaches() {
  return window['go']['cache']['Service']['ListCaches']();
}

export function PlanFor(arg1) {
  return window['go']['cache']['Service']['PlanFor'](arg1);
}

export function ReadCacheFile(arg1) {
  return window['go']['cache']['Service']['ReadCacheFile'](arg1);
}

export function WriteCacheFile(arg1, arg2) {
  return window['go']['cache']['Service']['WriteCacheFile'](arg1, arg2);
}
